### ISSUE TITLE
Problem with mini-css-extract-plugin/sass-loader(?) in CircleCI

### ISSUE THREAD

**Issue by andreydos** [frandiox/vue-graphql-enterprise-boilerplate#26]
When the project runs in CircleCI we get some errors:
I try to find some solutions but without success...  

```
 yarn run v1.7.0
$ cross-env ANALYZE=true yarn build
$ vue-cli-service build


 ERROR  Failed to compile with 6 errors          11:42:42

 error  in ./src/router/views/login/index.vue?vue&type=style&index=0&lang=scss&module=true

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/router/views/login/index.vue?vue&type=style&index=0&lang=scss&module=true 1:0-540 1:556-559 1:561-1098 1:561-1098
 @ ./src/router/views/login/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/app.vue?vue&type=style&index=0&lang=scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/app.vue?vue&type=style&index=0&lang=scss 1:0-463 1:479-482 1:484-944 1:484-944
 @ ./src/app.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/router/views/loading/index.vue?vue&type=style&index=0&lang=scss&module=true

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/router/views/loading/index.vue?vue&type=style&index=0&lang=scss&module=true 1:0-540 1:556-559 1:561-1098 1:561-1098
 @ ./src/router/views/loading/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/router/layouts/main.vue?vue&type=style&index=0&lang=scss&module=true

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/router/layouts/main.vue?vue&type=style&index=0&lang=scss&module=true 1:0-518 1:534-537 1:539-1054 1:539-1054
 @ ./src/router/layouts/main.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/nav-bar.vue?vue&type=style&index=0&lang=scss&module=true

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/components/nav-bar.vue?vue&type=style&index=0&lang=scss&module=true 1:0-500 1:516-519 1:521-1018 1:521-1018
 @ ./src/components/nav-bar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/router/layouts/main.vue?vue&type=script&lang=js
 @ ./src/router/layouts/main.vue?vue&type=script&lang=js
 @ ./src/router/layouts/main.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/components/nav-bar-routes.vue?vue&type=style&index=0&lang=scss&module=true

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

var colors = require('./colors');
^
      Invalid CSS after "v": expected 1 selector or at-rule, was "var colors = requir"
      in /home/circleci/frontend/node_modules/colors/lib/index.js (line 1, column 1)
    at runLoaders (/home/circleci/frontend/node_modules/webpack/lib/NormalModule.js:303:20)
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/home/circleci/frontend/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/home/circleci/frontend/node_modules/sass-loader/lib/loader.js:67:13)
    at Object.done [as callback] (/home/circleci/frontend/node_modules/neo-async/async.js:7974:18)
    at options.error (/home/circleci/frontend/node_modules/node-sass/lib/index.js:294:32)

 @ ./src/components/nav-bar-routes.vue?vue&type=style&index=0&lang=scss&module=true 1:0-507 1:523-526 1:528-1032 1:528-1032
 @ ./src/components/nav-bar-routes.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/components/nav-bar.vue?vue&type=script&lang=js
 @ ./src/components/nav-bar.vue?vue&type=script&lang=js
 @ ./src/components/nav-bar.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/router/layouts/main.vue?vue&type=script&lang=js
 @ ./src/router/layouts/main.vue?vue&type=script&lang=js
 @ ./src/router/layouts/main.vue
 @ ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/thread-loader/dist/cjs.js!./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue?vue&type=script&lang=js
 @ ./src/router/views/404/index.vue
 @ ./src/router/routes.js
 @ ./src/router/index.js
 @ ./src/main.js
 @ multi ./src/main.js

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1

**Comment by frandiox** [comment]
Didn't actually test CircliCI yet with the last changes in this repo. I'll try to have a look at it this weekend 👍

**Comment by frandiox** [comment]
@andreydos Hi! It is now passing in CircleCi: https://circleci.com/gh/frandiox/vue-graphql-enterprise-boilerplate/tree/master

After making some minor changes to the config file I didn't find this issue with `mini-css-extract-plugin` 🤔 I guess we can close this.

**Comment by andreydos** [comment]
@frandiox or I don't understand how to deal with CircleCI or its some magic :)

**Comment by andreydos** [comment]
@frandiox or I don't understand how to deal with CircleCI or its some magic :) I drop my fork and again fork you repo, add it in CircleCI its compile without problem. I make some changes and everything compiles fine( [https://circleci.com/gh/andreydos/vue-graphql-enterprise-boilerplate](url) ). I create an empty repo in GitHub clone it locally copy-paste each file from your repo fork, push it and add project in CircleCI... Build and tests fail! :) ( [https://circleci.com/gh/andreydos/clone-fork-template/tree/master](url) )

**Comment by andreydos** [comment]
using Travis I get same errors

**Comment by andreydos** [comment]
¯\\_(ツ)_/¯ and somehow it starts work :shipit:
